/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import almacenamiento.BaseDatos;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import procesos.ColorBotones;
import procesos.ColorPaneles;

/**
 *
 * @author Jhon
 */
public class MenuOpciones extends javax.swing.JFrame {

    private Menu menu;
    private AgregarComponente agregaComponente;
    private AgregarComputador creaCompu;
    private EditarComputador editaCompu;
    private EliminarComponente eliminaComponente;
    private EliminarComputador eliminaCompu;
    private ListaComputadores listaCompu;
    
    /**
     * Creates new form Menu
     */
    public MenuOpciones() {
        initComponents();
        new ColorPaneles(panelMenu);
        ColorBotones color = new ColorBotones();
        color.BotonTitulo(titulos);
        color.BotonTitulo(titulos1);
        color.BotonMenu(cancelar);
        color.BotonMenu(irProceso);
        color.BotonMenu(salir);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crud = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        titulos = new javax.swing.JLabel();
        equipos = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titulos1 = new javax.swing.JLabel();
        cancelar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radioCrear = new javax.swing.JRadioButton();
        radioEliminar = new javax.swing.JRadioButton();
        radioActualizar = new javax.swing.JRadioButton();
        radioVisualizar = new javax.swing.JRadioButton();
        irProceso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setMaximumSize(new java.awt.Dimension(1270, 720));
        setMinimumSize(new java.awt.Dimension(1270, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1270, 720));

        panelMenu.setBackground(new java.awt.Color(64, 75, 105));

        titulos.setBackground(new java.awt.Color(39, 37, 61));
        titulos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulos.setForeground(new java.awt.Color(255, 255, 255));
        titulos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulos.setText("MENÚ");
        titulos.setOpaque(true);

        equipos.setBackground(new java.awt.Color(40, 49, 73));
        equipos.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        equipos.setForeground(new java.awt.Color(102, 102, 102));
        equipos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equipos.setText("Equipo de computo");
        equipos.setOpaque(true);

        salir.setBackground(new java.awt.Color(40, 49, 73));
        salir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Shutdown_32px_1.png"))); // NOI18N
        salir.setText("Salir");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setIconTextGap(20);
        salir.setOpaque(true);
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulos, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(titulos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titulos1.setBackground(new java.awt.Color(39, 37, 61));
        titulos1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulos1.setForeground(new java.awt.Color(255, 255, 255));
        titulos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulos1.setText("EQUIPO DE COMPUTO");
        titulos1.setOpaque(true);

        cancelar.setBackground(new java.awt.Color(40, 49, 73));
        cancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Go_Back_32px.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar.setIconTextGap(20);
        cancelar.setOpaque(true);
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones a realizar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        radioCrear.setBackground(new java.awt.Color(220, 220, 230));
        crud.add(radioCrear);
        radioCrear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        radioCrear.setText("Crear");
        radioCrear.setIconTextGap(20);

        radioEliminar.setBackground(new java.awt.Color(220, 220, 230));
        crud.add(radioEliminar);
        radioEliminar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        radioEliminar.setText("Eliminar");
        radioEliminar.setIconTextGap(20);

        radioActualizar.setBackground(new java.awt.Color(220, 220, 230));
        crud.add(radioActualizar);
        radioActualizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        radioActualizar.setText("Actualizar");
        radioActualizar.setIconTextGap(20);

        radioVisualizar.setBackground(new java.awt.Color(220, 220, 230));
        crud.add(radioVisualizar);
        radioVisualizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        radioVisualizar.setText("Visualizar e imprimir");
        radioVisualizar.setIconTextGap(20);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radioEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioVisualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(radioCrear)
                .addGap(18, 18, 18)
                .addComponent(radioEliminar)
                .addGap(18, 18, 18)
                .addComponent(radioActualizar)
                .addGap(18, 18, 18)
                .addComponent(radioVisualizar)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        irProceso.setBackground(new java.awt.Color(40, 49, 73));
        irProceso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        irProceso.setForeground(new java.awt.Color(255, 255, 255));
        irProceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        irProceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8_Circled_Right_32px.png"))); // NOI18N
        irProceso.setText("Ir");
        irProceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irProceso.setIconTextGap(20);
        irProceso.setOpaque(true);
        irProceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                irProcesoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(titulos1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(irProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_cancelarMouseClicked

    private void irProcesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irProcesoMouseClicked

        Connection con = new BaseDatos().conecta();
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(MenuOpciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (radioCrear.isSelected() || radioEliminar.isSelected() || radioActualizar.isSelected() || radioVisualizar.isSelected()){
        this.setVisible(false);
            if (radioCrear.isSelected()) {
                if (equipos.getText().equals("Equipo de computo")) {
                    creaCompu.iniciadorVentanas();
                    creaCompu.setVisible(true);
                } else {
                    agregaComponente.iniciadorVentanas();
                    agregaComponente.setVisible(true);
                }
            } else if (radioEliminar.isSelected()) {
                if (equipos.getText().equals("Equipo de computo")) {
                    eliminaCompu.iniciadorVentanas();
                    eliminaCompu.setVisible(true);
                } else {
                    eliminaComponente.iniciadorVentanas();
                    eliminaComponente.setVisible(true);
                }
            } else if (radioActualizar.isSelected()) {
                editaCompu.iniciadorVentanas();
                editaCompu.setVisible(true);
            } else {
                listaCompu.iniciadorVentanas();
                listaCompu.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Se debe selecionar una de las opciones.", "Se genero un error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_irProcesoMouseClicked

    public void iniciadorVentanas(){
        menu = new Menu();
        agregaComponente = new AgregarComponente();
        creaCompu = new AgregarComputador();
        editaCompu = new EditarComputador();
        eliminaComponente = new EliminarComponente();
        eliminaCompu = new EliminarComputador();
        listaCompu = new ListaComputadores();
    }
    
    public void textoComponente(){
        equipos.setText("Componentes");
        titulos1.setText("Componentes informaticos");
        radioActualizar.setVisible(false);
        radioVisualizar.setVisible(false);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelar;
    private javax.swing.ButtonGroup crud;
    private javax.swing.JLabel equipos;
    private javax.swing.JLabel irProceso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton radioActualizar;
    private javax.swing.JRadioButton radioCrear;
    private javax.swing.JRadioButton radioEliminar;
    private javax.swing.JRadioButton radioVisualizar;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel titulos;
    private javax.swing.JLabel titulos1;
    // End of variables declaration//GEN-END:variables
}
